"""Reproduce the source register, uniform historical registration and review spec.
Run from any directory after the blueprint is current; inputs are retained rasters.
No production geometry is generated from this evidence recipe.
"""
from pathlib import Path
import json,hashlib,shutil
from PIL import Image
p=Path(__file__).resolve().parent;refs=p/'references';b=json.loads((p/'blueprint.json').read_text());deck=b['hull']['depth']-b['hull']['draft'];reg=json.loads((refs/'sources.json').read_text())
reg['policy']='Historical drawings and photographs inform manual original authoring. GameModels3D geometry is restricted to an isolated raster renderer. Production uses the versioned blueprint/catalog and original Python; no game offsets, attachment transforms, UVs, textures or geometry are authoring inputs.'
for source in reg['sources']:
 source.setdefault('document',source.get('type',source['id']));source.setdefault('status','retained source; interpretation and uncertainty recorded');source.setdefault('limits',source.get('limitations',''))
reg['sources'] += [dict(id='rmg-npb5265',url='https://prints.rmg.co.uk/products/body-plan-for-hms-king-george-v-1939-j9796',document='Vickers 1937 body plan NPB5265, with 1938 alterations; 4800 × 2659 museum scan J9796',status='Primary design drawing acquired; manually read for original section reconstruction',limits='Predates the 1941 as-fitted drawings. Half-section samples and fairing are interpreted, not recovered numerical offsets. Printed 28 ft design waterline differs from this model’s 29 ft standard-load datum. Ordinate origin remains approximately registered; 35 ft spacing is printed.'),dict(id='rmg-j9645-original',url='https://prints.rmg.co.uk/products/profile-plan-for-king-george-v-j9645',document='Vickers NPB5308 as-fitted profile, 12 July 1941; 4800 × 1233 original public museum scan',status='Primary drawing registered at one uniform LOA scale and keel datum',limits='Scanning, drawn lines and load differences retain about 1 m silhouette/height uncertainty. No independent vertical or component fitting.'),dict(id='rmg-n31777',url='https://prints.rmg.co.uk/products/hms-king-george-v-br-1939-under-way-bound-out-at-scapa-flow-2-april-1941-n31777',document='KGV leaving Scapa Flow, 2 April 1941, museum photograph N31777',status='Dated exterior appearance evidence',limits='Monochrome distant view; weathering and paint tones cannot be recovered colorimetrically.')]
# Avoid duplicated additions when the evidence recipe is rerun.
reg['sources']=list({q['id']:q for q in reg['sources']}.values())
(refs/'sources.json').write_text(json.dumps(reg,indent=2)+'\n')
# Retain the original images as well as one scale-registered presentation sheet.
profile=Image.open(refs/'historical/j9645-original.jpg').convert('RGB');top=Image.open(refs/'rmg-59266-j9646.jpg').convert('RGB')
ppm=(4579-207)/227.08;topScale=ppm/((1226-61)/227.08)
top=top.resize((round(top.width*topScale),round(top.height*topScale)),Image.Resampling.LANCZOS)
xOffset=round(2393-(61+1226)/2*topScale);topY=1290
sheet=Image.new('RGB',(4800,2500),'white');sheet.paste(profile,(0,0));sheet.paste(top,(xOffset,topY));sheet.save(refs/'historical/registered-plan-sheet.png')
from PIL import ImageDraw, ImageFont
im=profile.copy();draw=ImageDraw.Draw(im);font=ImageFont.truetype('/System/Library/Fonts/Supplemental/Arial.ttf',24)
for x in range(-110,111,10):
 px=2393+x*ppm;draw.line([(px,80),(px,1090)],fill='#879996',width=1);draw.text((px+4,80),str(x),fill='#135d52',font=font)
for z in range(-5,36,5):
 py=1041-8.8392*ppm-z*ppm;draw.line([(170,py),(4610,py)],fill='#879996',width=1);draw.text((4620,py-12),str(z)+'m',fill='#135d52',font=font)
im.save(refs/'historical/profile-measurement-grid.jpg')
history=dict(sourceId='rmg-j9645-original',image='historical/registered-plan-sheet.png',originalPixels=[4800,2500],method='Two independent original drawings assembled at one common metric scale. Profile unchanged, registered by LOA endpoints and keel. Upper deck uniformly resized once from its own complete LOA endpoints, then translated; no anisotropic stretching, skew correction or component fitting.',pixelsPerMeter=ppm,sternPixelX=207,bowPixelX=4579,starboard=dict(crop=[0,0,4800,1233],originPixel=[2393,1041-8.8392*ppm],keelPixelY=1041),port=dict(crop=[0,0,4800,1233],originPixel=[2393,1041-8.8392*ppm],keelPixelY=1041,mirrorX=True),top=dict(crop=[0,1290,4800,2500],originPixel=[2393,topY+160*topScale],mirrorX=False),uncertaintyPixels=8,limits='The port overlay mirrors the same starboard profile and does not certify side-specific fittings. Top drawing 1280 px; scale uncertainty larger than full-resolution profile. Original files are retained beside this derived presentation sheet.',componentSources=[dict(file='historical/j9645-original.jpg',scale=1,translation=[0,0]),dict(file='rmg-59266-j9646.jpg',scale=topScale,translation=[xOffset,topY])])
spec=dict(schemaVersion=1,revision='independent-1941-04',configuration=b['configuration'],authoringBoundary=reg['policy'],coordinates=dict(runtime='metres; +X starboard +Y up -Z bow',blender='metres; +X bow +Y port +Z up',conversion='runtime = (-blenderY, blenderZ, -blenderX)',origin='Overall-length midpoint at standard waterline',waterlineY=0,keelY=-8.8392,frameOriginM=113.54,frameRegistration=dict(basis='inferred',sourceId='rmg-npb5265',uncertaintyM=.8,note='Review sections use metres from the overall stern. Original body-plan ordinate no.1 is provisionally registered at Blender X=112 m, 35 ft spacing. These are distinct station systems.'),loadState='29 ft 1940 standard mean draft; not battle-day load/trim'),acceptance=[],dimensions=[],historicalRegistration=history,landmarks=[],probes=[dict(id='broadside',**{'from':[-30,0,0],'to':[0,0,0]}),dict(id='plunging',**{'from':[0,15,0],'to':[0,-5,0]}),dict(id='underwater',**{'from':[-30,-3.2,0],'to':[0,-3.2,0]})],sectionFrames=[30,55,113.54,163.54,205],review=dict(title='HMS King George V · early 1941',intro='Original reconstruction refined against Vickers schematics, dated photographs and GameModels3D raster views. Inspect the actual exported ship with matched cameras, retained originals and explicit source uncertainty.',historicalCredit='Royal Museums Greenwich / National Maritime Museum; Vickers-Armstrongs original drawings',historicalLabel='Vickers 1941 drawings · common metric scale / keel datum',limits='Body-plan sections are manual interpretations of a 1937/38 design drawing, not certified as-built offsets. Gunhouse, fitting dimensions and paint remain approximate. Game stock hull retains some later radar/light-AA details excluded from the 1941 reconstruction. CPU gunhouse armor retains a complete simplified face envelope behind the visible recessed ports.',images=[],sectionReference='j9796-original.jpg',evidenceImages=['j9796-original.jpg','j9645-original.jpg']))
for id,metric,target,source in [('length','hull.length',227.08,'rmg-b9'),('beam','hull.beam',31.3944,'rmg-slr1553'),('standard-draft','hull.draft',8.8392,'rmg-b9'),('waterline-length','hull.waterlineLength',225.6,'rmg-b9'),('midship-depth','hull.midshipDepth',15.5773,'rmg-b9')]:spec['acceptance'].append(dict(id=id,metric=metric,target=target,tolerance=.03,units='m',sourceId=source,basis='documented',evidenceUncertaintyM=.3 if id!='waterline-length' else 1.0))
catalog={part['id']:part for part in json.loads((p.parents[1]/'parts/guns.json').read_text())['parts']}
for m in b['mounts'][:3]:spec['landmarks'].append(dict(id=m['id']+'-axis',runtime=[m['position'][0],m['position'][1]+catalog[m['partId']]['pivotHeight'],m['position'][2]],sourceId='rmg-npb5308',basis='plan-measured',toleranceM=.8))
for id,x,z in [('funnel-cap',.8,deck+18),('foremast-top',8.5,37.8),('mainmast-top',-43.6,34.1),('fore-director',22.3,deck+16.35),('bridge-front',31,deck+16.95)]:spec['landmarks'].append(dict(id=id,runtime=[0,z,-x],sourceId='rmg-j9645-original',basis='plan-measured',toleranceM=1.5))
for selector,source,note in [('hull.sections','rmg-npb5265','Original manually read section samples, interpolated to 228 longitudinal stations. Rounded bilges, fine flared forebody and rising stern; design-versus-as-fitted and station-origin uncertainty remain.'),('structures','rmg-npb5316','Distinct tower trunk, projecting admiral/navigation cabins, signal wings and small service galleries replace repeated nested prisms.'),('mounts / catalog facets','rn-mkiii-plan','Revision 4 measures local raster proportions: longer main gunhouses, lower narrower roofs, aft quad crown, common Mk VII exposed barrel geometry and enlarged B barbette. RN plates 2/62 and IWM photographs guide form. See reports/visual-iteration-04/measurements.json for source disagreement and remaining uncertainty. Stable muzzle and joint IDs retained.'),('build.py fittings','rmg-npb5315','Open funnel jackets, searchlight galleries, rigging, boats, Carley floats, stairways, catapult/crane lattice and deck services are original interpreted details.'),('modules / compartments / armor','rmg-npb5265','Retained machinery IDs and positions. Five room envelopes reduced to fit the revised hull; flood spaces regenerated, protection clipped and hydrostatics recalibrated. Gameplay approximations remain.')]:spec['dimensions'].append(dict(selector=selector,sourceIds=[source],basis='estimated',valueLocation='blueprint.json / original author-blueprint.py / build.py / catalog',toleranceM=1.5,note=note))
for file,caption in [('historical/j9796-original.jpg','Vickers NPB5265 body plan · 1937/38 · design waterline 28 ft'),('historical/j9645-original.jpg','Vickers NPB5308 profile · as fitted July 1941'),('rmg-59266-j9646.jpg','Vickers upper deck · NPB5309'),('rmg-59272-j9647.jpg','Vickers shelter / boat decks · NPB5315'),('rmg-59273-j9648.jpg','Vickers bridge decks · NPB5316'),('rn-quadruple-turret-drawing.jpg','Royal Navy Mk III mounting · gunhouse plan'),('iwm-a3655-forward-turrets.jpg','IWM A3655 · forward battery and bridge · March 1941'),('historical/n31777-original.jpg','Royal Museums Greenwich N31777 · Scapa Flow · 2 April 1941')]:spec['review']['images'].append(dict(file=Path(file).name,alt=caption,caption=caption))
for file,caption in [('rn-mounting-section.jpg', 'Royal Navy plate 62: Mark II/III flashproofing arrangement (reproduced via Buxton / NavWeaps)'), ('rn-mounting-section-key.jpg', 'ADM 234/271 description for plate 62 (reproduced via Buxton / NavWeaps)'), ('iwm-a3905-pow-turrets.jpg', 'IWM A3905: Prince of Wales forward turrets, probably trials in 1941'), ('twm-mkiii-construction-1940.jpg', 'Tyne & Wear Archives DS.VA/9/PH/5/2: Mk III under construction, April 1940'), ('iwm-doy-turret-rear-construction.jpg', 'IWM: Duke of York turret under construction, reproduced on NavWeaps')]:spec['review']['images'].append(dict(file=file,alt=caption,caption=caption))
for im in spec['review']['images']:
 filename=im['file']
 if (refs/filename).exists():shutil.copyfile(refs/filename,refs/'historical'/filename)
(p/'modeling-spec.json').write_text(json.dumps(spec,indent=2)+'\n')
print('Original drawings, source register, matching registration and acceptance specification saved.')
