"""Rebuild the illustrated local guide from the versioned map recipes."""
import json
from pathlib import Path
from html import escape
maps = json.loads(Path('assets/maps/environments.v1.json').read_text())['maps']
root = Path('assets/maps/review')
notes = {
 'north-atlantic': ('Open water', 'The clearest battlefield: cool blue water, broken cloud, and an unobstructed horizon. The original smaller-wave tuning remains the reference for the other oceans.'),
 'pacific-islands': ('Island waters', 'A high sun lights turquoise water and pale sand. Forested islands frame a broad central channel, with smaller crests keeping the sea in scale with the ships.'),
 'arctic-passage': ('Snowy headlands', 'Low silver daylight, cold teal water, and heavier cloud cover give the northern passage a subdued atmosphere. Snow-covered headlands create strong silhouettes against the horizon.'),
 'indian-volcanic-coast': ('Volcanic coast', 'Dark ridges and recessed volcanic summits rise above indigo water. Lower afternoon light and atmospheric haze separate the coastal slopes from the distant horizon.')
}
style='''
@font-face{font-family:Barlow;src:url('fonts/barlow-latin-400-normal.woff2')}@font-face{font-family:BarlowCondensed;src:url('fonts/barlow-condensed-latin-500-normal.woff2')}
:root{color-scheme:dark;color:#edf1ec;background:#10232e;font-family:Barlow,sans-serif}*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:52px 32px}h1,h2{font-family:BarlowCondensed,sans-serif;font-weight:500;text-wrap:balance}h1{font-size:52px;margin:0}h2{font-size:34px;margin:0 0 8px}p{font-size:17px;line-height:1.65;max-width:68ch;color:#bacbd0}a{color:#e0c58d;text-underline-offset:4px}a:focus-visible,button:focus-visible,summary:focus-visible{outline:2px solid #e0c58d;outline-offset:5px}nav{display:flex;flex-wrap:wrap;gap:12px 24px;padding:20px 0;border-bottom:1px solid #47606a;margin-bottom:42px}article{scroll-margin-top:24px;margin-bottom:64px}figure{margin:20px 0}img{display:block;width:100%;height:auto;border-radius:3px}figcaption{font-size:14px;color:#bacbd0;line-height:1.5;margin-top:10px}.region{margin:0 0 16px}.detail{display:grid;grid-template-columns:1fr 1fr;gap:32px;align-items:start}.detail p{margin:0}dl{margin:0;display:grid;grid-template-columns:auto 1fr;gap:8px 20px;font-size:15px;line-height:1.5}dt{color:#bacbd0}dd{margin:0}.swatch{display:inline-block;width:12px;height:12px;border:1px solid #bacbd0;margin-right:8px;vertical-align:middle}summary{cursor:pointer;color:#e0c58d;font-size:18px;padding:16px 0}.table-scroll{overflow:auto}table{border-collapse:collapse;width:100%;font-size:15px;line-height:1.5}th,td{text-align:left;padding:12px;border-bottom:1px solid #47606a}th{color:#bacbd0;font-weight:400}.notes{border-top:1px solid #47606a;padding-top:24px}.notes p{font-size:15px}button{background:transparent;border:1px solid #80939a;border-radius:3px;color:#edf1ec;font:inherit;padding:10px 18px;min-height:44px;cursor:pointer}footer{margin-top:32px;color:#bacbd0;font-size:14px;line-height:1.5}@media(max-width:650px){main{padding:28px 18px}h1{font-size:38px}h2{font-size:30px}.detail{grid-template-columns:1fr;gap:20px}nav{gap:14px 20px}article{margin-bottom:44px}}@media print{:root{color-scheme:light;color:#182730;background:white}main{padding:0}nav,button{display:none}p,figcaption,dt,th,footer{color:#425961}a,summary{color:#182730}article{break-inside:avoid;break-before:page}h1{font-size:36px}h2{font-size:28px}.detail{gap:20px}p{font-size:14px}figure{margin:12px 0}img{max-height:48vh;object-fit:contain}}
'''
parts=['<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Four ocean battle maps — illustrated guide</title><style>'+style+'</style><main><header><h1>Four oceans to sail</h1><p>Distinct skies, smaller waves, and new coastlines for custom battles. Every image below comes from the actual game renderer.</p><p>In port, choose <strong>Custom battle → Battle waters</strong>, pick a map, then choose Fair, Moderate, or Heavy seas.</p></header><p><a href="landforms.html">Explore the landform before / after</a></p><nav aria-label="Maps">']
for m in maps: parts.append(f'<a href="#{m["id"]}">{escape(m["name"])}</a>')
parts.append('</nav>')
for m in maps:
 id=m['id']; sky=m['sky']; water=m['water']; title,description=notes[id]
 parts.append(f'''<article id="{id}"><h2>{escape(m['name'])}</h2><p class="region">{escape(m['region'])} · {title}</p><figure><a href="{id}.png" aria-label="Open full-size {escape(m['name'])} screenshot"><img src="{id}.png" width="1600" height="900" alt="Bismarck in {escape(m['name'])}: {escape(m['description'])}"></a><figcaption>Moderate seas · High quality · WebGPU · 1600 × 900 · Same camera and ocean tick across all four maps</figcaption></figure><div class="detail"><p>{description}</p><dl><dt>Sun</dt><dd>{sky['elevation']}° elevation</dd><dt>Cloud shape</dt><dd>{sky['coverage']} coverage control · {sky['altitude']:,} m altitude</dd><dt>Wave scale</dt><dd>{28*water['wavelengthScale']:g} m peak wavelength · {round(.45*water['amplitudeScale'],4):g} amplitude</dd><dt>Water color</dt><dd><span class="swatch" style="background:{water['waterColor']}"></span>{water['waterColor']}</dd><dt>Land</dt><dd>{len(m['land']['islands'])} authored islands / headlands</dd></dl></div></article>''')
parts.append('<section class="notes"><h2>How the maps play</h2><p>Each coastal map keeps a clear shipping lane for the two fleets. Larger rosters widen the lane automatically. Coastlines appear on the navigation chart; ships stop at shore and can reverse away. Bots steer away from nearby land. Low shells and torpedoes hit the coast, while shells with enough elevation can pass over it.</p><p>Sea conditions adjust the selected map’s waves. Returning to port restores the sheltered harbor and its daylight. These are original, region-inspired game landscapes, not replicas of surveyed places.</p><details><summary>Compare shader settings</summary><div class="table-scroll"><table><thead><tr><th>Map</th><th>Sun elevation / azimuth</th><th>Wind (Moderate)</th><th>Foam opacity</th><th>Haze turbidity</th><th>Fog range</th></tr></thead><tbody>')
for m in maps:
 parts.append(f'<tr><th scope="row">{m["name"]}</th><td>{m["sky"]["elevation"]}° / {m["sky"]["azimuth"]}°</td><td>{9*m["water"]["windScale"]:g}</td><td>{m["water"]["foam"]}</td><td>{m["sky"]["turbidity"]}</td><td>{m["fog"]["start"]/1000:g}–{m["fog"]["end"]/1000:g} km</td></tr>')
parts.append('</tbody></table></div><p>Amplitude is a multiplier, not a wave height in meters. Cloud coverage is a nonlinear shader control, not the percentage of visible sky. Atmospheres and collision envelopes are artistic gameplay approximations. Grounding damage, tides, detailed seabed simulation, and global bot route planning are not implemented.</p></details><p><a href="../environments.v1.json">Versioned map definitions</a> · <a href="README.md">Capture and validation notes</a></p><button onclick="window.print()">Print / save PDF</button></section><footer>Captured September 6, 2026. Original map recipes and screenshots are retained under assets/maps. Eroded landforms reuse the retained CC0 harbor ground and tree textures.</footer></main></html>')
(root/'index.html').write_text(''.join(parts))
