// Generated by scripts/multiplayer/generate-rust-definitions.ts from src/ships/blueprint.ts.
// Regenerate when the authoring contract changes; do not maintain a second schema.
use serde::{Deserialize, Serialize};
pub type Vec3 = [f64; 3];

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct FireProfile {
    #[serde(rename = "fuelSeconds")]
    pub fuel_seconds: f64,
    #[serde(rename = "ignitionHeat")]
    pub ignition_heat: f64,
    #[serde(rename = "heatPerDamage")]
    pub heat_per_damage: f64,
    #[serde(rename = "ventPosition")]
    pub vent_position: Option<[f64; 3]>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GunPartBallistics {
    #[serde(rename = "dragPerSecond")]
    pub drag_per_second: f64,
    #[serde(rename = "dispersionRad")]
    pub dispersion_rad: f64,
    #[serde(rename = "muzzleSpeedSigmaFraction")]
    pub muzzle_speed_sigma_fraction: Option<f64>,
    #[serde(rename = "penetrationReferenceSpeedMps")]
    pub penetration_reference_speed_mps: Option<f64>,
    #[serde(rename = "basis")]
    pub basis: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct APProjectile {
    #[serde(rename = "armingResistanceMm")]
    pub arming_resistance_mm: f64,
    #[serde(rename = "fuzeDelaySeconds")]
    pub fuze_delay_seconds: f64,
    #[serde(rename = "explosiveKg")]
    pub explosive_kg: f64,
    #[serde(rename = "fragmentPenetrationMm")]
    pub fragment_penetration_mm: f64,
    #[serde(rename = "basis")]
    pub basis: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct HEProjectile {
    #[serde(rename = "explosiveKg")]
    pub explosive_kg: f64,
    #[serde(rename = "fragmentPenetrationMm")]
    pub fragment_penetration_mm: f64,
    #[serde(rename = "damage")]
    pub damage: f64,
    #[serde(rename = "stockFraction")]
    pub stock_fraction: f64,
    #[serde(rename = "basis")]
    pub basis: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GunPartGunhouseShape {
    #[serde(rename = "footprint")]
    pub footprint: Vec<[f64; 2]>,
    #[serde(rename = "roof")]
    pub roof: Vec<[f64; 3]>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GunPartGunhouseMeshFacesItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "indices")]
    pub indices: [f64; 3],
    #[serde(rename = "thicknessMm")]
    pub thickness_mm: f64,
    #[serde(rename = "material")]
    pub material: String,
    #[serde(rename = "finish")]
    pub finish: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GunPartGunhouseMeshProvenance {
    #[serde(rename = "sourceId")]
    pub source_id: String,
    #[serde(rename = "basis")]
    pub basis: String,
    #[serde(rename = "note")]
    pub note: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GunPartGunhouseMesh {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "vertices")]
    pub vertices: Vec<[f64; 3]>,
    #[serde(rename = "faces")]
    pub faces: Vec<GunPartGunhouseMeshFacesItem>,
    #[serde(rename = "provenance")]
    pub provenance: Option<GunPartGunhouseMeshProvenance>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct GunPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "massKg")]
    pub mass_kg: f64,
    #[serde(rename = "barbetteRadius")]
    pub barbette_radius: f64,
    #[serde(rename = "gunhouseSize")]
    pub gunhouse_size: [f64; 3],
    #[serde(rename = "pivotHeight")]
    pub pivot_height: f64,
    #[serde(rename = "trunnionForward")]
    pub trunnion_forward: f64,
    #[serde(rename = "muzzleForward")]
    pub muzzle_forward: f64,
    #[serde(rename = "barrelSpacing")]
    pub barrel_spacing: f64,
    #[serde(rename = "caliberM")]
    pub caliber_m: f64,
    #[serde(rename = "traverseDeg")]
    pub traverse_deg: f64,
    #[serde(rename = "traverseRateDeg")]
    pub traverse_rate_deg: f64,
    #[serde(rename = "elevationMinDeg")]
    pub elevation_min_deg: f64,
    #[serde(rename = "elevationMaxDeg")]
    pub elevation_max_deg: f64,
    #[serde(rename = "elevationRateDeg")]
    pub elevation_rate_deg: f64,
    #[serde(rename = "reloadSeconds")]
    pub reload_seconds: f64,
    #[serde(rename = "muzzleSpeed")]
    pub muzzle_speed: f64,
    #[serde(rename = "projectileMassKg")]
    pub projectile_mass_kg: f64,
    #[serde(rename = "penetrationMm")]
    pub penetration_mm: f64,
    #[serde(rename = "damage")]
    pub damage: f64,
    #[serde(rename = "recoilM")]
    pub recoil_m: f64,
    #[serde(rename = "ammoPerBarrel")]
    pub ammo_per_barrel: f64,
    #[serde(rename = "armorMm")]
    pub armor_mm: f64,
    #[serde(rename = "ballistics")]
    pub ballistics: Option<GunPartBallistics>,
    #[serde(rename = "ap")]
    pub ap: Option<APProjectile>,
    #[serde(rename = "he")]
    pub he: Option<HEProjectile>,
    #[serde(rename = "barrelCount")]
    pub barrel_count: Option<f64>,
    #[serde(rename = "barrelVerticalSpacing")]
    pub barrel_vertical_spacing: Option<f64>,
    #[serde(rename = "mountingStyle")]
    pub mounting_style: Option<String>,
    #[serde(rename = "barrelBaseRadius")]
    pub barrel_base_radius: Option<f64>,
    #[serde(rename = "rangefinderWidth")]
    pub rangefinder_width: Option<f64>,
    #[serde(rename = "rangefinderForward")]
    pub rangefinder_forward: Option<f64>,
    #[serde(rename = "gunhouseBaseHeight")]
    pub gunhouse_base_height: Option<f64>,
    #[serde(rename = "rollerRadius")]
    pub roller_radius: Option<f64>,
    #[serde(rename = "gunhouseShape")]
    pub gunhouse_shape: Option<GunPartGunhouseShape>,
    #[serde(rename = "gunhouseMesh")]
    pub gunhouse_mesh: Option<GunPartGunhouseMesh>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct MountDefinition {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partId")]
    pub part_id: String,
    #[serde(rename = "battery")]
    pub battery: String,
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "bearingDeg")]
    pub bearing_deg: f64,
    #[serde(rename = "rangefinder")]
    pub rangefinder: bool,
    #[serde(rename = "parentMountId")]
    pub parent_mount_id: Option<String>,
    #[serde(rename = "traverseDeg")]
    pub traverse_deg: Option<f64>,
    #[serde(rename = "magazineId")]
    pub magazine_id: Option<String>,
    #[serde(rename = "fire")]
    pub fire: Option<FireProfile>,
    #[serde(rename = "weapon")]
    pub weapon: GunPart,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TorpedoPart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "diameterM")]
    pub diameter_m: f64,
    #[serde(rename = "lengthM")]
    pub length_m: f64,
    #[serde(rename = "speed")]
    pub speed: f64,
    #[serde(rename = "rangeM")]
    pub range_m: f64,
    #[serde(rename = "armingDistanceM")]
    pub arming_distance_m: f64,
    #[serde(rename = "runningDepthM")]
    pub running_depth_m: f64,
    #[serde(rename = "reloadSeconds")]
    pub reload_seconds: f64,
    #[serde(rename = "launchIntervalSeconds")]
    pub launch_interval_seconds: f64,
    #[serde(rename = "damage")]
    pub damage: f64,
    #[serde(rename = "breachAreaM2")]
    pub breach_area_m2: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TubeDefinition {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partId")]
    pub part_id: String,
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "bearingDeg")]
    pub bearing_deg: f64,
    #[serde(rename = "arcDeg")]
    pub arc_deg: f64,
    #[serde(rename = "ammo")]
    pub ammo: f64,
    #[serde(rename = "magazineId")]
    pub magazine_id: String,
    #[serde(rename = "launcherModuleId")]
    pub launcher_module_id: Option<String>,
    #[serde(rename = "launcherId")]
    pub launcher_id: Option<String>,
    #[serde(rename = "weapon")]
    pub weapon: TorpedoPart,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct DepthChargePart {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "diameterM")]
    pub diameter_m: f64,
    #[serde(rename = "lengthM")]
    pub length_m: f64,
    #[serde(rename = "sinkSpeed")]
    pub sink_speed: f64,
    #[serde(rename = "detonationDepthM")]
    pub detonation_depth_m: f64,
    #[serde(rename = "blastRadiusM")]
    pub blast_radius_m: f64,
    #[serde(rename = "reloadSeconds")]
    pub reload_seconds: f64,
    #[serde(rename = "launchIntervalSeconds")]
    pub launch_interval_seconds: f64,
    #[serde(rename = "damage")]
    pub damage: f64,
    #[serde(rename = "breachAreaM2")]
    pub breach_area_m2: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ChargeDefinition {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "partId")]
    pub part_id: String,
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "velocity")]
    pub velocity: [f64; 3],
    #[serde(rename = "ammo")]
    pub ammo: f64,
    #[serde(rename = "magazineId")]
    pub magazine_id: String,
    #[serde(rename = "launcherModuleId")]
    pub launcher_module_id: Option<String>,
    #[serde(rename = "weapon")]
    pub weapon: DepthChargePart,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct DamageControlProfile {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "teams")]
    pub teams: f64,
    #[serde(rename = "setupSeconds")]
    pub setup_seconds: f64,
    #[serde(rename = "repairPoints")]
    pub repair_points: f64,
    #[serde(rename = "roomFuelSeconds")]
    pub room_fuel_seconds: f64,
    #[serde(rename = "mountFuelSeconds")]
    pub mount_fuel_seconds: f64,
    #[serde(rename = "suppressionPerSecond")]
    pub suppression_per_second: f64,
    #[serde(rename = "portablePumpM3PerSecond")]
    pub portable_pump_m3_per_second: f64,
    #[serde(rename = "repairHpPerSecond")]
    pub repair_hp_per_second: f64,
    #[serde(rename = "repairCeiling")]
    pub repair_ceiling: f64,
    #[serde(rename = "patchM2PerSecond")]
    pub patch_m2_per_second: f64,
    #[serde(rename = "maxPatchM2")]
    pub max_patch_m2: f64,
    #[serde(rename = "flashProtection")]
    pub flash_protection: f64,
    #[serde(rename = "basis")]
    pub basis: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionUnderwaterProtectionZonesItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "damageReduction")]
    pub damage_reduction: f64,
    #[serde(rename = "breachReduction")]
    pub breach_reduction: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionUnderwaterProtection {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "basis")]
    pub basis: String,
    #[serde(rename = "zones")]
    pub zones: Vec<ShipDefinitionUnderwaterProtectionZonesItem>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct DamageRegion {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "durabilityFraction")]
    pub durability_fraction: f64,
    #[serde(rename = "mountId")]
    pub mount_id: Option<String>,
    #[serde(rename = "moduleId")]
    pub module_id: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionLocalDamage {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "regions")]
    pub regions: Vec<DamageRegion>,
    #[serde(rename = "basis")]
    pub basis: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionStability {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "dryCenterOfGravity")]
    pub dry_center_of_gravity: [f64; 3],
    #[serde(rename = "buoyancyScale")]
    pub buoyancy_scale: f64,
    #[serde(rename = "shellThicknessMm")]
    pub shell_thickness_mm: f64,
    #[serde(rename = "basis")]
    pub basis: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct HullSectionsItem {
    #[serde(rename = "station")]
    pub station: f64,
    #[serde(rename = "points")]
    pub points: Vec<[f64; 2]>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Hull {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "length")]
    pub length: f64,
    #[serde(rename = "beam")]
    pub beam: f64,
    #[serde(rename = "draft")]
    pub draft: f64,
    #[serde(rename = "depth")]
    pub depth: f64,
    #[serde(rename = "massKg")]
    pub mass_kg: f64,
    #[serde(rename = "waterplaneAreaM2")]
    pub waterplane_area_m2: f64,
    #[serde(rename = "reserveBuoyancyM3")]
    pub reserve_buoyancy_m3: f64,
    #[serde(rename = "halfBreadths")]
    pub half_breadths: Vec<[f64; 2]>,
    #[serde(rename = "deckHeights")]
    pub deck_heights: Vec<[f64; 2]>,
    #[serde(rename = "keelHeights")]
    pub keel_heights: Vec<[f64; 2]>,
    #[serde(rename = "sections")]
    pub sections: Option<Vec<HullSectionsItem>>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Handling {
    #[serde(rename = "forwardSpeed")]
    pub forward_speed: f64,
    #[serde(rename = "reverseSpeed")]
    pub reverse_speed: f64,
    #[serde(rename = "acceleration")]
    pub acceleration: f64,
    #[serde(rename = "braking")]
    pub braking: f64,
    #[serde(rename = "rudderRate")]
    pub rudder_rate: f64,
    #[serde(rename = "maxYawRate")]
    pub max_yaw_rate: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ArmorPlate {
    #[serde(rename = "vertices")]
    pub vertices: Vec<[f64; 3]>,
    #[serde(rename = "material")]
    pub material: String,
    #[serde(rename = "mountId")]
    pub mount_id: Option<String>,
    #[serde(rename = "exterior")]
    pub exterior: Option<bool>,
    #[serde(rename = "surfaceId")]
    pub surface_id: Option<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Armor {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "thicknessMm")]
    pub thickness_mm: f64,
    #[serde(rename = "exterior")]
    pub exterior: Option<bool>,
    #[serde(rename = "plate")]
    pub plate: Option<ArmorPlate>,
    #[serde(rename = "provenance")]
    pub provenance: Option<GunPartGunhouseMeshProvenance>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct TorpedoLauncher {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "traverseRateDeg")]
    pub traverse_rate_deg: f64,
    #[serde(rename = "launchArcsDeg")]
    pub launch_arcs_deg: Vec<[f64; 2]>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct SubmarineDefinitionAppendages {
    #[serde(rename = "bowPlanes")]
    pub bow_planes: Vec<String>,
    #[serde(rename = "sternPlanes")]
    pub stern_planes: Vec<String>,
    #[serde(rename = "rudders")]
    pub rudders: Vec<String>,
    #[serde(rename = "propellers")]
    pub propellers: Vec<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct SubmarineDefinition {
    #[serde(rename = "submergedHandling")]
    pub submerged_handling: Handling,
    #[serde(rename = "ballastCapacityM3")]
    pub ballast_capacity_m3: f64,
    #[serde(rename = "neutralBallastFraction")]
    pub neutral_ballast_fraction: f64,
    #[serde(rename = "floodRateM3PerSecond")]
    pub flood_rate_m3_per_second: f64,
    #[serde(rename = "blowRateM3PerSecond")]
    pub blow_rate_m3_per_second: f64,
    #[serde(rename = "emergencyBlowRateM3PerSecond")]
    pub emergency_blow_rate_m3_per_second: f64,
    #[serde(rename = "maxDiveSpeed")]
    pub max_dive_speed: f64,
    #[serde(rename = "maxRiseSpeed")]
    pub max_rise_speed: f64,
    #[serde(rename = "periscopeDepthM")]
    pub periscope_depth_m: f64,
    #[serde(rename = "maxDepthM")]
    pub max_depth_m: f64,
    #[serde(rename = "maxTorpedoDepthM")]
    pub max_torpedo_depth_m: f64,
    #[serde(rename = "periscopeEye")]
    pub periscope_eye: [f64; 3],
    #[serde(rename = "surfaceEngineIds")]
    pub surface_engine_ids: Vec<String>,
    #[serde(rename = "submergedEngineIds")]
    pub submerged_engine_ids: Vec<String>,
    #[serde(rename = "appendages")]
    pub appendages: SubmarineDefinitionAppendages,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct FlightDeckLayoutSpotsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "preferredRole")]
    pub preferred_role: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct FlightDeckLayoutElevatorsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "hangarY")]
    pub hangar_y: f64,
    #[serde(rename = "widthM")]
    pub width_m: f64,
    #[serde(rename = "lengthM")]
    pub length_m: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct FlightDeckLayout {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "surfaceId")]
    pub surface_id: String,
    #[serde(rename = "spots")]
    pub spots: Vec<FlightDeckLayoutSpotsItem>,
    #[serde(rename = "launchStart")]
    pub launch_start: [f64; 3],
    #[serde(rename = "launchEnd")]
    pub launch_end: [f64; 3],
    #[serde(rename = "recoveryTouchdown")]
    pub recovery_touchdown: [f64; 3],
    #[serde(rename = "recoveryStop")]
    pub recovery_stop: [f64; 3],
    #[serde(rename = "elevators")]
    pub elevators: Vec<FlightDeckLayoutElevatorsItem>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AirWingDefinitionSquadronsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "modelId")]
    pub model_id: String,
    #[serde(rename = "role")]
    pub role: String,
    #[serde(rename = "count")]
    pub count: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AirWingDefinition {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "launchPosition")]
    pub launch_position: [f64; 3],
    #[serde(rename = "recoveryPosition")]
    pub recovery_position: [f64; 3],
    #[serde(rename = "serviceModuleId")]
    pub service_module_id: String,
    #[serde(rename = "launchIntervalSeconds")]
    pub launch_interval_seconds: f64,
    #[serde(rename = "rearmSeconds")]
    pub rearm_seconds: f64,
    #[serde(rename = "flightSize")]
    pub flight_size: Option<f64>,
    #[serde(rename = "deckCapacity")]
    pub deck_capacity: Option<f64>,
    #[serde(rename = "maxActiveFlights")]
    pub max_active_flights: Option<f64>,
    #[serde(rename = "deckLayout")]
    pub deck_layout: Option<FlightDeckLayout>,
    #[serde(rename = "squadrons")]
    pub squadrons: Vec<AirWingDefinitionSquadronsItem>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipRigEnsignsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "design")]
    pub design: String,
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "width")]
    pub width: f64,
    #[serde(rename = "staffHeight")]
    pub staff_height: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipRigRadarsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "nodeId")]
    pub node_id: String,
    #[serde(rename = "rpm")]
    pub rpm: f64,
    #[serde(rename = "sweepDeg")]
    pub sweep_deg: Option<f64>,
    #[serde(rename = "phaseDeg")]
    pub phase_deg: Option<f64>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipRig {
    #[serde(rename = "version")]
    pub version: f64,
    #[serde(rename = "ensigns")]
    pub ensigns: Vec<ShipRigEnsignsItem>,
    #[serde(rename = "radars")]
    pub radars: Vec<ShipRigRadarsItem>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Module {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "hp")]
    pub hp: f64,
    #[serde(rename = "compartmentId")]
    pub compartment_id: Option<String>,
    #[serde(rename = "placement")]
    pub placement: Option<String>,
    #[serde(rename = "torpedoLauncherId")]
    pub torpedo_launcher_id: Option<String>,
    #[serde(rename = "protectionMm")]
    pub protection_mm: Option<f64>,
    #[serde(rename = "servesMountIds")]
    pub serves_mount_ids: Option<Vec<String>>,
    #[serde(rename = "immersionToleranceM")]
    pub immersion_tolerance_m: Option<f64>,
    #[serde(rename = "role")]
    pub role: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct CompartmentCellsItem {
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Compartment {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "capacityM3")]
    pub capacity_m3: f64,
    #[serde(rename = "pumpM3PerSecond")]
    pub pump_m3_per_second: f64,
    #[serde(rename = "fire")]
    pub fire: Option<FireProfile>,
    #[serde(rename = "cells")]
    pub cells: Option<Vec<CompartmentCellsItem>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct FloodConnectionBounds {
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct FloodConnection {
    #[serde(rename = "id")]
    pub id: Option<String>,
    #[serde(rename = "fromId")]
    pub from_id: String,
    #[serde(rename = "toId")]
    pub to_id: String,
    #[serde(rename = "areaM2")]
    pub area_m2: f64,
    #[serde(rename = "state")]
    pub state: Option<String>,
    #[serde(rename = "position")]
    pub position: Option<[f64; 3]>,
    #[serde(rename = "armorId")]
    pub armor_id: Option<String>,
    #[serde(rename = "bounds")]
    pub bounds: Option<FloodConnectionBounds>,
    #[serde(rename = "thicknessMm")]
    pub thickness_mm: Option<f64>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct PropulsionGroup {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "share")]
    pub share: f64,
    #[serde(rename = "boilerIds")]
    pub boiler_ids: Vec<String>,
    #[serde(rename = "driveIds")]
    pub drive_ids: Vec<String>,
    #[serde(rename = "shaftIds")]
    pub shaft_ids: Vec<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionPropulsion {
    #[serde(rename = "groups")]
    pub groups: Vec<PropulsionGroup>,
    #[serde(rename = "basis")]
    pub basis: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionFloodRegionsItem {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
    #[serde(rename = "compartmentId")]
    pub compartment_id: String,
    #[serde(rename = "face")]
    pub face: Option<String>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Volume {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "center")]
    pub center: [f64; 3],
    #[serde(rename = "size")]
    pub size: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionMountEnvelope {
    #[serde(rename = "beam")]
    pub beam: f64,
    #[serde(rename = "length")]
    pub length: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AuthoredStructureExhaust {
    #[serde(rename = "position")]
    pub position: [f64; 3],
    #[serde(rename = "width")]
    pub width: f64,
    #[serde(rename = "length")]
    pub length: f64,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AuthoredSurface {
    #[serde(rename = "vertices")]
    pub vertices: Vec<[f64; 3]>,
    #[serde(rename = "triangles")]
    pub triangles: Vec<[f64; 3]>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct AuthoredStructure {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "footprint")]
    pub footprint: Vec<[f64; 2]>,
    #[serde(rename = "baseY")]
    pub base_y: f64,
    #[serde(rename = "height")]
    pub height: f64,
    #[serde(rename = "material")]
    pub material: String,
    #[serde(rename = "exhaust")]
    pub exhaust: Option<AuthoredStructureExhaust>,
    #[serde(rename = "surface")]
    pub surface: Option<AuthoredSurface>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionStructuralPlating {
    #[serde(rename = "hullMm")]
    pub hull_mm: f64,
    #[serde(rename = "superstructureMm")]
    pub superstructure_mm: f64,
    #[serde(rename = "note")]
    pub note: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionViewpoints {
    #[serde(rename = "bridge")]
    pub bridge: [f64; 3],
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinitionAccuracy {
    #[serde(rename = "exterior")]
    pub exterior: String,
    #[serde(rename = "internals")]
    pub internals: String,
    #[serde(rename = "weapons")]
    pub weapons: String,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct ShipDefinition {
    #[serde(rename = "compilerVersion")]
    pub compiler_version: f64,
    #[serde(rename = "mounts")]
    pub mounts: Vec<MountDefinition>,
    #[serde(rename = "torpedoTubes")]
    pub torpedo_tubes: Option<Vec<TubeDefinition>>,
    #[serde(rename = "depthChargeLaunchers")]
    pub depth_charge_launchers: Option<Vec<ChargeDefinition>>,
    #[serde(rename = "schemaVersion")]
    pub schema_version: f64,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "configuration")]
    pub configuration: String,
    #[serde(rename = "coordinates")]
    pub coordinates: String,
    #[serde(rename = "modelUrl")]
    pub model_url: String,
    #[serde(rename = "damageControl")]
    pub damage_control: Option<DamageControlProfile>,
    #[serde(rename = "underwaterProtection")]
    pub underwater_protection: Option<ShipDefinitionUnderwaterProtection>,
    #[serde(rename = "localDamage")]
    pub local_damage: Option<ShipDefinitionLocalDamage>,
    #[serde(rename = "stability")]
    pub stability: Option<ShipDefinitionStability>,
    #[serde(rename = "hull")]
    pub hull: Hull,
    #[serde(rename = "handling")]
    pub handling: Handling,
    #[serde(rename = "armor")]
    pub armor: Vec<Armor>,
    #[serde(rename = "torpedoLaunchers")]
    pub torpedo_launchers: Option<Vec<TorpedoLauncher>>,
    #[serde(rename = "submarine")]
    pub submarine: Option<SubmarineDefinition>,
    #[serde(rename = "airWing")]
    pub air_wing: Option<AirWingDefinition>,
    #[serde(rename = "rig")]
    pub rig: Option<ShipRig>,
    #[serde(rename = "modules")]
    pub modules: Vec<Module>,
    #[serde(rename = "compartments")]
    pub compartments: Vec<Compartment>,
    #[serde(rename = "connections")]
    pub connections: Vec<FloodConnection>,
    #[serde(rename = "propulsion")]
    pub propulsion: Option<ShipDefinitionPropulsion>,
    #[serde(rename = "floodRegions")]
    pub flood_regions: Option<Vec<ShipDefinitionFloodRegionsItem>>,
    #[serde(rename = "obstructions")]
    pub obstructions: Vec<Volume>,
    #[serde(rename = "mountEnvelope")]
    pub mount_envelope: Option<ShipDefinitionMountEnvelope>,
    #[serde(rename = "structures")]
    pub structures: Option<Vec<AuthoredStructure>>,
    #[serde(rename = "structuralPlating")]
    pub structural_plating: Option<ShipDefinitionStructuralPlating>,
    #[serde(rename = "viewpoints")]
    pub viewpoints: Option<ShipDefinitionViewpoints>,
    #[serde(rename = "accuracy")]
    pub accuracy: ShipDefinitionAccuracy,
}
