/** Compile the existing definition type into Rust input types. No second authoring schema. */
import ts from 'typescript';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { mkdir } from 'node:fs/promises';
const source = 'src/ships/blueprint.ts';
const program = ts.createProgram([source], { strict: true, target: ts.ScriptTarget.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler, module: ts.ModuleKind.ESNext });
const checker = program.getTypeChecker();
const file = program.getSourceFile(source)!;
const declaration = file.statements.find(s => ts.isInterfaceDeclaration(s) && s.name.text === 'ShipDefinition')!;
const root = checker.getTypeAtLocation(declaration);
const definitions: string[] = [];
const assigned = new Map<ts.Type, string>();
const names = new Set<string>();
const snake = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();
const pascal = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
function rustType(original: ts.Type, hint: string): string {
  let type = original;
  if (type.isUnion()) {
    const members = type.types.filter(t => !(t.flags & (ts.TypeFlags.Undefined | ts.TypeFlags.Null)));
    if (members.length === 1) return rustType(members[0], hint);
    if (members.every(t => !!(t.flags & ts.TypeFlags.StringLike))) return 'String';
    if (members.every(t => !!(t.flags & ts.TypeFlags.NumberLike))) return 'f64';
    if (members.every(t => !!(t.flags & ts.TypeFlags.BooleanLike))) return 'bool';
    throw new Error(`Unsupported union ${hint}: ${checker.typeToString(type)}`);
  }
  if (type.flags & ts.TypeFlags.StringLike) return 'String';
  if (type.flags & ts.TypeFlags.NumberLike) return 'f64';
  if (type.flags & ts.TypeFlags.BooleanLike) return 'bool';
  if (checker.isTupleType(type)) {
    const types = checker.getTypeArguments(type as ts.TypeReference).map((t,i) => rustType(t, hint + i));
    if (new Set(types).size === 1) return `[${types[0]}; ${types.length}]`;
    return `(${types.join(', ')})`;
  }
  if (checker.isArrayType(type)) return `Vec<${rustType(checker.getTypeArguments(type as ts.TypeReference)[0], hint + 'Item')}>`;
  const prior = assigned.get(type);
  if (prior) return prior;
  const symbolName = type.aliasSymbol?.name ?? type.symbol?.name;
  let name = symbolName && !symbolName.startsWith('__') && !['Omit','Partial','Pick'].includes(symbolName) ? symbolName : hint;
  if (name === 'ShipDefinitionMountsItem') name = 'MountDefinition';
  if (name === 'ShipDefinitionTorpedoTubesItem') name = 'TubeDefinition';
  if (name === 'ShipDefinitionDepthChargeLaunchersItem') name = 'ChargeDefinition';
  if (names.has(name)) name = hint;
  if (names.has(name)) throw new Error(`Duplicate name ${name}`);
  names.add(name); assigned.set(type, name);
  const fields = checker.getPropertiesOfType(type).map(property => {
    const location = property.valueDeclaration ?? property.declarations?.[0];
    if (!location) throw new Error(`No declaration ${name}.${property.name}`);
    const field = snake(property.name);
    const optional = !!(property.flags & ts.SymbolFlags.Optional);
    const fieldType = rustType(checker.getTypeOfSymbolAtLocation(property, location), name + pascal(property.name));
    const identifier = ['type','ref','match','mod','loop','move','where','in','self','use','fn'].includes(field) ? 'r#' + field : field;
    return `    #[serde(rename = "${property.name}")]\n    pub ${identifier}: ${optional ? `Option<${fieldType}>` : fieldType},`;
  });
  definitions.push(`#[derive(Clone, Debug, Default, Serialize, Deserialize)]\npub struct ${name} {\n${fields.join('\n')}\n}\n`);
  return name;
}
rustType(root, 'ShipDefinition');
await mkdir('crates/naval-sim/src', { recursive: true });
await Bun.write('crates/naval-sim/src/definition.rs', '// Generated by scripts/multiplayer/generate-rust-definitions.ts from src/ships/blueprint.ts.\n// Regenerate when the authoring contract changes; do not maintain a second schema.\nuse serde::{Deserialize, Serialize};\npub type Vec3 = [f64; 3];\n\n' + definitions.join('\n'));
const format = Bun.spawn([join(homedir(), '.cargo', 'bin', 'rustfmt'), '--edition', '2024', 'crates/naval-sim/src/definition.rs'], { stdout: 'inherit', stderr: 'inherit' });
if (await format.exited) throw new Error('Rust definition formatting failed.');
console.log(`Generated ${definitions.length} Rust definition types.`);
