import { COMPONENT_MATERIAL_INPUTS } from '../../src/ships/componentMaterials';
import { readFile, mkdir, writeFile, rename, rm } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { Matrix4, Quaternion, Vector3 } from 'three';
import { barrelIds, barrelOffset, barrelHeightOffset } from '../../src/ships/blueprint';
import type { ConstructionEquipmentPart, GunPart, Vec3 } from '../../src/ships/blueprint';
import { readLibrary, componentHash } from './library';

/** Authoring inputs omit only fields generated by publication. No duplicate weapon data. */
export type EquipmentSource = Omit<ConstructionEquipmentPart, 'modelUrl' | 'contentHash'>;
interface Builder { path: string; function: string; inputs: string[] }
interface EquipmentRegistry { schemaVersion: 1; builders: Record<string, Builder>; components: { partId: string; builder: string; review: 'unreviewed'|'accepted'; limitations: string }[] }
export interface EquipmentNode { id: string; parentId?: string; localMatrix: number[]; worldMatrix: number[] }
export interface ModelInspection { boundsCenter: Vec3; size: Vec3; nodes: EquipmentNode[]; triangles: number; textureCount: number }
export const digest = (bytes: string | Uint8Array) => createHash('sha256').update(bytes).digest('hex');
const originalPath = (path: string) => /^(assets\/parts|scripts\/ships)\/[a-zA-Z0-9_./-]+\.py$/.test(path) && !path.split('/').includes('..');
const finiteVec = (v: unknown): v is Vec3 => Array.isArray(v) && v.length === 3 && v.every(Number.isFinite);
const safeId = (id: string) => /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(id);
export async function readEquipment(root: string) {
  const [{ library, catalog }, source, registry] = await Promise.all([
    readLibrary(root), readFile(join(root, 'assets/parts/construction.json'), 'utf8').then(JSON.parse),
    readFile(join(root, 'assets/parts/construction-library.json'), 'utf8').then(JSON.parse),
  ]);
  const equipment = source.equipment as EquipmentSource[];
  if (source.schemaVersion !== 1 || registry.schemaVersion !== 1 || !Array.isArray(equipment)) throw new Error('Unsupported equipment source');
  const ids = new Set<string>();
  for (const p of equipment) {
    if (!safeId(p.id) || ids.has(p.id)) throw new Error(`Duplicate or invalid equipment ID: ${p.id}`);
    ids.add(p.id);
    if (!['gun','torpedo-launcher','engine','magazine','funnel','propeller','rudder','mast','director','deck-fitting'].includes(p.kind)) throw new Error(`Invalid equipment family: ${p.id}`);
    if (!p.name || !finiteVec(p.size) || p.size.some(x => x <= 0) || !finiteVec(p.boundsCenter) || !finiteVec(p.centerOfGravity)) throw new Error(`Invalid equipment dimensions: ${p.id}`);
    if (!['internal','deck','underwater'].includes(p.placement)) throw new Error(`Invalid equipment placement: ${p.id}`);
    if (p.path) {
      const profile = p.path;
      if (p.kind !== 'deck-fitting' || p.placement !== 'deck' || !['railing','rope','chain'].includes(profile.kind)
        || !Number.isFinite(profile.diameterM) || profile.diameterM <= 0 || profile.diameterM > .5
        || !Number.isFinite(profile.massKgPerM) || profile.massKgPerM <= 0 || profile.massKgPerM > 1000
        || (profile.kind === 'railing' && (!Number.isFinite(profile.heightM) || profile.heightM! <= 0 || profile.heightM! > 3
          || !Number.isFinite(profile.postSpacingM) || profile.postSpacingM! < .25 || profile.postSpacingM! > 3
          || !Number.isFinite(profile.postMassKg) || profile.postMassKg! <= 0))) throw new Error(`Invalid path profile: ${p.id}`);
    }
    if (p.kind === 'gun') {
      if (p.massKg !== undefined || !catalog.parts.some(g => g.id === p.gunPartId) || !library.components.some(e => e.partId === p.gunPartId && e.builder)) throw new Error(`Gun must reference an original canonical variant: ${p.id}`);
    } else {
      if (!Number.isFinite(p.massKg) || p.massKg! <= 0) throw new Error(`Missing equipment mass: ${p.id}`);
      const entry = registry.components.find((e: {partId: string}) => e.partId === p.id);
      if (!entry || !registry.builders[entry.builder] || !['unreviewed','accepted'].includes(entry.review) || !entry.limitations) throw new Error(`No registered original equipment builder: ${p.id}`);
    }
    for (const volume of p.occupancy ?? []) if (!finiteVec(volume.center) || !finiteVec(volume.size) || volume.size.some(v => v <= 0)) throw new Error(`Invalid occupancy: ${p.id}`);
    if (p.fitting && (p.kind !== 'deck-fitting' || p.path || !p.fitting.length || p.fitting.length > 64 || p.fitting.some(b => !finiteVec(b.center) || !finiteVec(b.size) || b.size.some(v => v <= 0)))) throw new Error(`Invalid fitting boxes: ${p.id}`);
    const sockets = new Set<string>();
    for (const s of p.sockets ?? []) {
      if (!safeId(s.id) || sockets.has(s.id) || !s.kind || !finiteVec(s.position) || !finiteVec(s.direction) || Math.abs(Math.hypot(...s.direction)-1) > 1e-6) throw new Error(`Invalid socket: ${p.id}`);
      sockets.add(s.id);
    }
    for (const key of ['powerKw','exhaustKw','thrustEfficiency','rudderAreaM2','serviceMassKg','ammunitionCapacity'] as const) if (p[key] !== undefined && (!Number.isFinite(p[key]) || p[key]! < 0)) throw new Error(`Invalid ${key}: ${p.id}`);
    if (p.kind === 'torpedo-launcher' && (!catalog.torpedoes?.some(t => t.id === p.torpedoPartId) || !p.tubeOffsets?.length || p.tubeOffsets.some(v => !finiteVec(v)))) throw new Error(`Invalid torpedo launcher: ${p.id}`);
  }
  for (const b of Object.values(registry.builders) as Builder[]) if (!originalPath(b.path) || !/^[a-z_]+$/.test(b.function) || !Array.isArray(b.inputs) || b.inputs.some(p => !originalPath(p))) throw new Error('Non-original equipment builder path');
  return { equipment, registry: registry as EquipmentRegistry, library, catalog };
}
export async function equipmentInputs(root: string, id: string) {
  const { registry } = await readEquipment(root);
  const entry = registry.components.find(e => e.partId === id);
  if (!entry) throw new Error(`Unknown non-gun equipment: ${id}`);
  const b = registry.builders[entry.builder];
  return [...COMPONENT_MATERIAL_INPUTS, 'assets/parts/construction.json','assets/parts/construction-library.json','assets/parts/construction/library.py', b.path, ...b.inputs];
}
export async function equipmentHash(root: string, part: EquipmentSource) {
  const { registry, library, catalog } = await readEquipment(root);
  if (part.kind === 'gun') {
    const entry = library.components.find(e => e.partId === part.gunPartId)!;
    return componentHash(root, library, entry, catalog.parts.find(p => p.id === part.gunPartId)!);
  }
  const entry = registry.components.find(e => e.partId === part.id)!;
  const b = registry.builders[entry.builder];
  const paths = [...COMPONENT_MATERIAL_INPUTS, 'assets/parts/construction/library.py', b.path, ...b.inputs, 'scripts/parts/equipment_build.py', 'scripts/ships/export.py', 'scripts/ships/blender_batching.py'];
  return digest(JSON.stringify([1, part, entry, b, ...await Promise.all(paths.map(p => readFile(join(root,p),'utf8')))]));
}
export async function buildEquipment(root: string, part: EquipmentSource) {
  if (part.kind === 'gun') {
    const child = Bun.spawn(['bun', join(root,'scripts/parts/pipeline.ts'),'build',part.gunPartId!],{cwd:root,stdout:'inherit',stderr:'inherit'});
    if (await child.exited) throw new Error(`Gun build failed: ${part.id}`);
    return;
  }
  const output = join(root,'.build/parts',part.id), stage = output+'.staging';
  const hash = await equipmentHash(root,part);
  await mkdir(join(root,'.build/parts'),{recursive:true});
  await mkdir(stage).catch(() => { throw new Error(`Build running or interrupted: ${stage}; inspect before removing`); });
  const definition = join(stage,'definition.json');
  await writeFile(definition,JSON.stringify({schemaVersion:1,contentHash:hash,equipment:part,sockets:part.sockets}));
  const blender = process.env.BLENDER_BIN ?? (existsSync('/Applications/Blender.app/Contents/MacOS/Blender')?'/Applications/Blender.app/Contents/MacOS/Blender':'blender');
  const child = Bun.spawn([blender,'--background','--factory-startup','--python-exit-code','1','--python',join(root,'scripts/parts/equipment_build.py')],{cwd:root,env:{...process.env,SHIP_OUTPUT:stage,SHIP_DEFINITION:definition},stdout:'pipe',stderr:'pipe'});
  const [stdout,stderr,code] = await Promise.all([new Response(child.stdout).text(),new Response(child.stderr).text(),child.exited]);
  await writeFile(join(stage,'build.log'),stdout+stderr);
  if (code) throw new Error(`Blender failed (${code}): ${stage}/build.log`);
  const latest = (await readEquipment(root)).equipment.find(p => p.id === part.id);
  if (!latest || await equipmentHash(root,latest) !== hash) throw new Error('Equipment inputs changed during build');
  inspectEquipmentModel(await readFile(join(stage,'model.glb')),hash,part);
  await mkdir(output,{recursive:true});
  for (const file of ['definition.json','source.blend','build.log','model.glb']) await rename(join(stage,file),join(output,file));
  await rm(stage,{recursive:true});
}

/** Reads the actual exported hierarchy and vertex bounds, never source-model estimates. */
export function inspectEquipmentModel(bytes: Buffer, hash: string, part?: EquipmentSource, weapon?: GunPart): ModelInspection {
  if (bytes.length < 28 || bytes.readUInt32LE(0) !== 0x46546c67 || bytes.readUInt32LE(4) !== 2 || bytes.readUInt32LE(8) !== bytes.length) throw new Error('Invalid component GLB');
  const jsonLength = bytes.readUInt32LE(12), end = 20+jsonLength;
  if (end+8 > bytes.length || bytes.readUInt32LE(16) !== 0x4e4f534a) throw new Error('Invalid component GLB JSON');
  const doc = JSON.parse(bytes.subarray(20,end).toString());
  if (doc.scenes?.[doc.scene ?? 0]?.extras?.definitionHash !== hash) throw new Error('Stale component definitionHash');
  if (doc.buffers?.length !== 1 || doc.buffers[0].uri || doc.images?.some((i: any) => i.uri)) throw new Error('Component must embed all buffers/textures');
  if (bytes.readUInt32LE(end+4) !== 0x004e4942) throw new Error('Missing component binary chunk');
  const bin = bytes.subarray(end+8);
  const byId = new Map<string,EquipmentNode>(), matrices = new Map<number,Matrix4>();
  let triangles = 0;
  const min = [Infinity,Infinity,Infinity], max = [-Infinity,-Infinity,-Infinity];
  const readVec = (accessorIndex: number, visit: (v: Vector3) => void) => {
    const a=doc.accessors[accessorIndex], v=doc.bufferViews[a.bufferView];
    if (a.type !== 'VEC3' || a.componentType !== 5126 || a.sparse || !v || v.buffer !== 0) throw new Error('Unsupported component position encoding');
    const offset=(v.byteOffset ?? 0)+(a.byteOffset ?? 0), stride=v.byteStride ?? 12;
    if (offset+(a.count-1)*stride+12 > bin.length) throw new Error('Invalid position buffer bounds');
    for(let i=0;i<a.count;i++) visit(new Vector3(...[0,4,8].map(k=>bin.readFloatLE(offset+i*stride+k)) as Vec3));
  };
  const visit = (index:number,parent:Matrix4,parentId?:string) => {
    if (matrices.has(index)) throw new Error('Component hierarchy has duplicate nodes');
    const n=doc.nodes[index];
    const local = n.matrix ? new Matrix4().fromArray(n.matrix) : new Matrix4().compose(new Vector3(...(n.translation ?? [0,0,0])),new Quaternion(...(n.rotation ?? [0,0,0,1])),new Vector3(...(n.scale ?? [1,1,1])));
    const world=parent.clone().multiply(local);matrices.set(index,world);
    const id=n.extras?.nodeId;
    if (id) {
      if (!/^component\.[a-zA-Z0-9_.-]+$/.test(id) || byId.has(id)) throw new Error(`Invalid or duplicate component node: ${id}`);
      byId.set(id,{id,...(parentId?{parentId}:{}),localMatrix:local.toArray(),worldMatrix:world.toArray()});
    }
    if (n.mesh !== undefined) for (const primitive of doc.meshes[n.mesh].primitives) {
      if ((primitive.mode ?? 4) !== 4) throw new Error('Non-triangle component primitive');
      triangles += (primitive.indices === undefined ? doc.accessors[primitive.attributes.POSITION].count : doc.accessors[primitive.indices].count)/3;
      const positions: Vec3[] = [];
      readVec(primitive.attributes.POSITION,v => {
        v.applyMatrix4(world);
        v.toArray().forEach((x,k)=>{if(!Number.isFinite(x))throw new Error('Non-finite component geometry');min[k]=Math.min(min[k],x);max[k]=Math.max(max[k],x);});
        if (part?.fitting) positions.push(v.toArray() as Vec3);
      });
      if (part?.fitting) {
        let indices = positions.map((_, i) => i);
        if (primitive.indices !== undefined) {
          const a = doc.accessors[primitive.indices], view = doc.bufferViews[a.bufferView];
          const width = { 5121: 1, 5123: 2, 5125: 4 }[a.componentType as 5121 | 5123 | 5125];
          if (!width || a.type !== 'SCALAR' || a.sparse || view.buffer !== 0) throw new Error('Unsupported component index encoding');
          const offset = (view.byteOffset ?? 0) + (a.byteOffset ?? 0);
          indices = Array.from({ length: a.count }, (_, i) => bin.readUIntLE(offset + i * (view.byteStride ?? width), width));
        }
        for (let i = 0; i < indices.length; i += 3) {
          const triangle = indices.slice(i, i + 3).map(index => positions[index]);
          if (triangle.length !== 3 || !part.fitting.some(box => triangle.every(point => point && point.every((v, k) => Math.abs(v - box.center[k]) <= box.size[k] / 2 + .001)))) throw new Error(`${part.id}: original fitting boxes do not enclose every visible triangle`);
        }
      }
    }
    for (const child of n.children ?? []) visit(child,world,id ?? parentId);
  };
  for (const i of doc.scenes[doc.scene ?? 0].nodes ?? []) visit(i,new Matrix4());
  if (!triangles || triangles > 500000 || bytes.length > 30*1024*1024) throw new Error('Component exceeds model budget or has no geometry');
  if (part?.kind === 'gun' && weapon) {
    for (const suffix of ['yaw',...barrelIds(weapon).flatMap(b=>[`${b}.elevation`,`${b}.recoil`,`${b}.muzzle`])]) if (!byId.has(`component.${suffix}`)) throw new Error(`Missing gun joint/socket: ${suffix}`);
    const posedWorld = (id: string, changes: Map<string,Matrix4>): Matrix4 => {
      const node = byId.get(id)!;
      const local = changes.get(id) ?? new Matrix4().fromArray(node.localMatrix);
      return node.parentId ? posedWorld(node.parentId,changes).multiply(local) : local.clone();
    };
    for (const [i,b] of barrelIds(weapon).entries()) {
      const pitch=byId.get(`component.${b}.elevation`)!, recoil=byId.get(`component.${b}.recoil`)!, muzzle=byId.get(`component.${b}.muzzle`)!;
      if (pitch.parentId !== 'component.yaw' || recoil.parentId !== pitch.id || muzzle.parentId !== recoil.id) throw new Error(`Invalid gun hierarchy: ${b}`);
      for (const [bearing,elevation,recoilFraction] of [[0,0,0],[-73,12,.5],[127,weapon.elevationMaxDeg,.9],[37,weapon.elevationMinDeg,1]]) {
        const yawAngle=bearing*Math.PI/180, angle=elevation*Math.PI/180;
        const replaceRotation = (id:string,rotation:Matrix4) => rotation.setPosition(new Vector3().setFromMatrixPosition(new Matrix4().fromArray(byId.get(id)!.localMatrix)));
        const recoiled=new Matrix4().fromArray(recoil.localMatrix);recoiled.elements[14] += weapon.recoilM*recoilFraction;
        const changes = new Map([['component.yaw',replaceRotation('component.yaw',new Matrix4().makeRotationY(-yawAngle))],[pitch.id,replaceRotation(pitch.id,new Matrix4().makeRotationX(angle))],[recoil.id,recoiled]]);
        const actual=new Vector3().setFromMatrixPosition(posedWorld(muzzle.id,changes));
        const length=weapon.muzzleForward-weapon.trunnionForward-weapon.recoilM*recoilFraction, vertical=barrelHeightOffset(weapon,i), lateral=barrelOffset(weapon,i);
        const forward=weapon.trunnionForward+length*Math.cos(angle)-vertical*Math.sin(angle);
        const expected=new Vector3(Math.cos(yawAngle)*lateral+Math.sin(yawAngle)*forward,weapon.pivotHeight+vertical*Math.cos(angle)+length*Math.sin(angle),Math.sin(yawAngle)*lateral-Math.cos(yawAngle)*forward);
        if (actual.distanceTo(expected)>.025) throw new Error(`Gun muzzle mismatch at ${bearing}/${elevation}/${recoilFraction}: ${b}, error ${actual.distanceTo(expected)} m`);
      }
    }
  } else if (part) {
    for (const suffix of ['root',...(part.kind==='propeller'?['spin']:['rudder','director','torpedo-launcher'].includes(part.kind)?['yaw']:[]),...(part.tubeOffsets ?? []).map((_,i)=>`tube-${i+1}.muzzle`),...(part.sockets ?? []).map(s=>`socket.${s.id}`)]) if (!byId.has('component.'+suffix)) throw new Error(`Missing equipment joint/socket: ${suffix}`);
    for (const [i,offset] of (part.tubeOffsets ?? []).entries()) {
      const node=byId.get(`component.tube-${i+1}.muzzle`)!;
      if (node.parentId !== 'component.yaw' || new Vector3().setFromMatrixPosition(new Matrix4().fromArray(node.worldMatrix)).distanceTo(new Vector3(...offset))>.001) throw new Error('Torpedo muzzle transform mismatch');
    }
  }
  return {boundsCenter:min.map((x,k)=>(x+max[k])/2) as Vec3,size:min.map((x,k)=>max[k]-x) as Vec3,nodes:[...byId.values()],triangles,textureCount:doc.images?.length ?? 0};
}
